"""Public API for the EMS Material Manager."""

from .adapters import EMotorSolutionProjectAdapter, EMSolutionInputAdapter
from .audit import MaterialAuditIssue, audit_material, audit_materials
from .errors import (
    GuiDependencyError,
    LegacyImportError,
    ManagerConfigurationError,
    MaterialAlreadyExistsError,
    MaterialConflictError,
    MaterialManagerError,
    MaterialNotFoundError,
    MaterialParseError,
    ModelValidationError,
    OpenDataImportError,
    PropertyNotFoundError,
    ReadOnlyMaterialError,
    RepositoryCorruptionError,
    SchemaValidationError,
    UnitConversionError,
)
from .exchange import (
    ORIGIN_KEY,
    ExportSelection,
    ProductMaterialAdapter,
    ProductMaterialSnapshot,
    SnapshotOrigin,
    document_sha256,
    exported_payload_sha256,
    material_sha256,
    origin_from_payload,
)
from .legacy import (
    LegacyImportResult,
    import_legacy_material_document,
    load_legacy_material,
)
from .manager import MaterialManager
from .magnetic import (
    BH_CURVE_PATH,
    RELATIVE_PERMEABILITY_PATH,
    MagneticCharacteristic,
    MagneticCharacteristicKind,
    resolve_magnetic_characteristic,
)
from .material_types import (
    MaterialTemplate,
    MaterialTypeCatalog,
    MaterialTypeDefinition,
    TemplateProperty,
    load_material_type_catalog,
)
from .model import (
    Axis,
    ConditionValue,
    CurveProperty,
    Material,
    MaterialIdentity,
    MaterialProperty,
    PropertySource,
    Provenance,
    ScalarProperty,
    ValidityRange,
    VersionMetadata,
)
from .open_data import (
    CandidateCatalog,
    OpenDataImportResult,
    SourceManifest,
    import_csv_recipe,
    sha256_file,
)
from .property_catalog import (
    PropertyCatalog,
    PropertyDefinition,
    load_property_catalog,
)
from .repository import (
    ConfiguredMaterialRepository,
    JsonMaterialRepository,
    MaterialRepository,
)
from .serialization import (
    load_material,
    material_from_dict,
    material_from_json,
    material_to_json,
    save_material,
    schema_document,
    validate_document,
)
from .units import canonical_unit, convert_value, supported_units, unit_dimension
from .validation import MaterialValidationResult, validate_material

__all__ = [
    "BH_CURVE_PATH",
    "ORIGIN_KEY",
    "RELATIVE_PERMEABILITY_PATH",
    "Axis",
    "CandidateCatalog",
    "ConditionValue",
    "ConfiguredMaterialRepository",
    "CurveProperty",
    "EMSolutionInputAdapter",
    "EMotorSolutionProjectAdapter",
    "ExportSelection",
    "GuiDependencyError",
    "JsonMaterialRepository",
    "LegacyImportError",
    "LegacyImportResult",
    "ManagerConfigurationError",
    "MagneticCharacteristic",
    "MagneticCharacteristicKind",
    "Material",
    "MaterialAlreadyExistsError",
    "MaterialAuditIssue",
    "MaterialConflictError",
    "MaterialIdentity",
    "MaterialManager",
    "MaterialManagerError",
    "MaterialNotFoundError",
    "MaterialParseError",
    "MaterialProperty",
    "MaterialRepository",
    "MaterialTemplate",
    "MaterialTypeCatalog",
    "MaterialTypeDefinition",
    "MaterialValidationResult",
    "ModelValidationError",
    "OpenDataImportError",
    "OpenDataImportResult",
    "ProductMaterialAdapter",
    "ProductMaterialSnapshot",
    "PropertyCatalog",
    "PropertyDefinition",
    "PropertyNotFoundError",
    "PropertySource",
    "Provenance",
    "ReadOnlyMaterialError",
    "RepositoryCorruptionError",
    "ScalarProperty",
    "SchemaValidationError",
    "SnapshotOrigin",
    "SourceManifest",
    "TemplateProperty",
    "UnitConversionError",
    "ValidityRange",
    "VersionMetadata",
    "audit_material",
    "audit_materials",
    "canonical_unit",
    "convert_value",
    "document_sha256",
    "exported_payload_sha256",
    "import_csv_recipe",
    "import_legacy_material_document",
    "load_legacy_material",
    "load_material",
    "load_material_type_catalog",
    "load_property_catalog",
    "material_from_dict",
    "material_from_json",
    "material_sha256",
    "material_to_json",
    "origin_from_payload",
    "resolve_magnetic_characteristic",
    "save_material",
    "schema_document",
    "sha256_file",
    "supported_units",
    "unit_dimension",
    "validate_document",
    "validate_material",
]
